-- AlterTable
ALTER TABLE `Order` ADD COLUMN `coin1` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `coin10` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `coin15` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `coin2` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `coin20` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `coin50` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `money100` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `money20` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `money200` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `money50` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `money500` DOUBLE NOT NULL DEFAULT 0;
